@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.edwinmindcraft.apoli.common.condition.configuration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;